### ISSUE TITLE
context.fail! not working on Rails 6.0

### ISSUE THREAD

**Issue by rbazinet** [collectiveidea/interactor#203]
I am having an issue where I use an organizer with 6 interactors. If one of the interactors fails, I expect the rest to not be run.

I have code that calls `context.fail!` but it appears to not work with Rails 6. The exact same code works fine with Rails 5.2.x. 

Anyone experience this problem?

**Comment by d3mash** [comment]
Hi! Can you please provide a reproducible snippet?

**Comment by rstacruz** [comment]
@rbazinet, I'm not sure about Rails 6, but there's an open issue about `fail!` errors that might be relevant: #170

**Comment by aliahmadexe** [comment]
@rbazinet  hey!
i upgraded my project from 5.2 to 6.1 and context.fail! is giving me  undefined method `empty?' for nil:NilClass
did you solve the problem in rails 6?
